# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bootstrap_builders 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "bootstrap_builders"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["kaspernj"]
  s.date = "2016-01-17"
  s.description = "A library to generate Bootstrap HTML for Rails."
  s.email = "k@spernj.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/bootstrap_builders.rb",
    "lib/bootstrap_builders/box.rb",
    "lib/bootstrap_builders/button.rb",
    "lib/bootstrap_builders/helpers.rb",
    "spec/bootstrap_builders/box_spec.rb",
    "spec/bootstrap_builders/button_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/working_helpers.rb"
  ]
  s.homepage = "http://github.com/kaspernj/bootstrap_builders"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A library to generate Bootstrap HTML for Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<html_gen>, [">= 0.0.6"])
      s.add_runtime_dependency(%q<auto_autoloader>, [">= 0.0.4"])
      s.add_development_dependency(%q<rspec>, ["~> 3.4.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<best_practice_project>, [">= 0"])
      s.add_development_dependency(%q<rubocop>, ["= 0.36.0"])
    else
      s.add_dependency(%q<html_gen>, [">= 0.0.6"])
      s.add_dependency(%q<auto_autoloader>, [">= 0.0.4"])
      s.add_dependency(%q<rspec>, ["~> 3.4.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<best_practice_project>, [">= 0"])
      s.add_dependency(%q<rubocop>, ["= 0.36.0"])
    end
  else
    s.add_dependency(%q<html_gen>, [">= 0.0.6"])
    s.add_dependency(%q<auto_autoloader>, [">= 0.0.4"])
    s.add_dependency(%q<rspec>, ["~> 3.4.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<best_practice_project>, [">= 0"])
    s.add_dependency(%q<rubocop>, ["= 0.36.0"])
  end
end

